api_version = "2025-07"
name = "Offer Product Discount"
type = "function"
handle = "offer-product-discount"

[build]
command = "javy build src/run.js -o dist/function.wasm"
path = "dist/function.wasm"

[[targeting]]
target = "purchase.product-discount.run"
input_query = "input-queries/run.graphql"
export = "run"

[ui]
enable_create = true
