api_version = "2025-07"

[[extensions]]
name = "Compare At Discount"
handle = "offer-product-discount"
type = "function"
description = "Applies discounts based on compare-at price"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui]
  enable_create = true
