query RunInput {
  cart {
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
          currencyCode
        }
        compareAtAmountPerQuantity {
          amount
          currencyCode
        }
      }
      merchandise {
        ... on ProductVariant {
          id
          product {
            id
            handle
            hasAnyTag(tags: ["offer-discount"])
          }
        }
      }
    }
  }
  discountNode {
    metafield(namespace: "offer-config", key: "settings") {
      value
    }
  }
}
